### ISSUE TITLE
this is not available in the firefox extensions online list?

### ISSUE THREAD

**Issue by gl00ten** [akhilkedia/youtube-dl-firefox-addon#1]
this is not available in the firefox extensions online list?

**Comment by akhilkedia** [comment]
No, I did not upload this to the firefox addons website as I was not sure whether this downloader will violate some of their policies.

The extension can however be downloaded from the github here https://github.com/akhilkedia/youtube-dl-firefox-addon/blob/master/command_runner-1.0-an+fx-linux.xpi?raw=true
