### ISSUE TITLE
queued downloads and download list

### ISSUE THREAD

**Issue by ousia** [akhilkedia/youtube-dl-firefox-addon#10]
@akhilkedia,

many thanks for your add-on. I have two questions about downloaded files.

1. Is the download list stored somewhere?
1. If I cancel a running download of queued files (by closing Firefox), is the list of pending files stored somewhere?

Many  thanks for your help.

**Comment by akhilkedia** [comment]
1. No
2. No

**Comment by ousia** [comment]
@akhilkedia,

in that case, how knows the add-on know what to download next in the queue?

Many thanks for your help.
