### ISSUE TITLE
Improvement to installation instructions

### ISSUE THREAD

**Issue by rrthomas** [akhilkedia/youtube-dl-firefox-addon#11]
Thanks very much for this extension, which was the first one I was able to get to work. Very handy for downloading videos in low quality to watch on an old machine!

One thing that would make the installation easier is if the default path in the `firefox_command_runner.json` file used the directory `youtube-dl-firefox-addon`, which is the default name when the repo is cloned, rather than `firefox-command-runner`. Took me a bit of thinking to work this out!

**Comment by akhilkedia** [comment]
Its leftover code from earlier versions of this addon.
I'll clarify it in the instructions in the README.
