### ISSUE TITLE
How to make it work on Linux?

### ISSUE THREAD

**Issue by Jzarecta** [akhilkedia/youtube-dl-firefox-addon#2]
I didnt get to the original path since the example seems in OSX. However the Linux path has a different name.

However there is no instructions on how to use it, I only get a logo on the toolbar with no ioptions.

**Comment by akhilkedia** [comment]
The original paths are all for linux. I have only tested this on Ubuntu, but it should work on all linux platforms.
I have updated the path in the install instructions to make things clearer.
I have also added instructions on how to use it in the README here https://github.com/akhilkedia/youtube-dl-firefox-addon/blob/master/README.md#how-to-use-this-addon
