### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by mtnjustme** [akhilkedia/youtube-dl-firefox-addon#4]
ain't gonna write code for it, but in general :
different fields for youtube-dl arguements, for video and audio, instead of 1 field that goes for both of them.
option to choose a converted format in case the found format isn't the same one (lets say mp4 is the best video and the converted format chose by the user is mkv, so converting the mp4 to mkv).
add metadata option (--add-metadata).
if you ask me, the options default formats and quick download audio formats should be removed, youtube-dl 2 fields (audio and video), and naming the file is whats important, all the other options should be placed as check boxes.

other stuff :
add whether to embed thumbnail or not (--embed-thumbnail) specifically to audio.
if file exist ask if to overwrite, also a checkbox in the settings page if whether to overwrite automatically or not or ask everytime (not checked (not filled), checked (v), ask everytime (filled, looks like a filled black square inside the checkbox)).

also add open windows folder or open file if possible

great addon.

**Comment by akhilkedia** [comment]
Most issues mentioned above can be fixed by simply modifying youtube-dl's own config.

**Comment by akhilkedia** [comment]
And for any other of the above suggested features, feel free to send a PR.

**Comment by mtnjustme** [comment]
my bad, i confused this with another repo :
https://github.com/marklieberman/youtube-dl-button
seems almost the same repo in the basic idea.
