### ISSUE TITLE
problem getting to run under (non-debian style) linux

### ISSUE THREAD

**Issue by igel-kun** [akhilkedia/youtube-dl-firefox-addon#5]
hey man, nice idea. I do, however, have issues getting it to run under Gentoo Linux. I have zero experience in debugging firefox addons, so I'm just writing here I guess.
When I press the addon button in firefox, nothing happens. I tried uncommenting the line that sends a 'Download Started'-message, but no notification happens in firefox. I verified that youtube-dl works properly on the command-line for the user that runs firefox and that the ```firefox-command-runner.py``` script is executable by that same user. I also verified that ```firefox_command_runner.json``` is in "${HOME}/.mozilla/native-messaging-hosts" (doesn't need execute right, does it?) and its "path" variable is correct.

**Comment by akhilkedia** [comment]
You seem to have checked all basic troubleshooting boxes.

The only solution I can think of is to debug the extension itself using the steps here - 
https://extensionworkshop.com/documentation/develop/debugging/#debugging-background-scripts

Specifically - 
1. Go to `about:debugging`
2. Click `Inspect` next to Command Runner
3. Go to console tab, clear it (the dustbin icon on the top-left). We do this to get rid of any-preexisting firefox error messages in the console.
4. Go to debugger tab, click `command Runner`, click `background.js`
5. Set a breakpoint on line 32 of `background.js` (which says `port.postMessage(tab.url);`)
6. In a new tab, go to any Youtube page and click the extension icon.
7. Go back to the debugger tab and check it says on the right side "paused on breakpoint" and line 32 is highlighted
7. You can now continue the debugging(by pressing the play icon on the top right), and check if any error messages are printed on the console.

Also, can you check `/usr/bin/python --version`? It should say `Python 2.x.xx`

**Comment by igel-kun** [comment]
yes! Thanks, the last comment was the game-changer, it seems indeed related to python 2 vs 3 (I have installed both on my machine). I recommend thus changing the shebang to
`#!/usr/bin/env python2` in [line 1](https://github.com/akhilkedia/youtube-dl-firefox-addon/blob/master/app/firefox-command-runner.py#L1)

**Comment by akhilkedia** [comment]
Solved via https://github.com/akhilkedia/youtube-dl-firefox-addon/pull/7
