### ISSUE TITLE
suggestion: give youtube-dl access to firefox's cookie jar

### ISSUE THREAD

**Issue by igel-kun** [akhilkedia/youtube-dl-firefox-addon#6]
Often, videos that ```youtube-dl``` is capable of downloading are restricted to certain accounts and the authentication is done via cookies set by the sites on login. As ```youtube-dl``` has, per se, nothing to do with ```firefox```, it cannot natively access such cookies. However, ```youtube-dl``` has a ```--cookies``` option that takes the location of a cookie jar so, in theory it should be possible for an addon to extract the cookies into some file and give that to ```youtube-dl```. Since I have zero experience in addon coding, I'll leave this here :)

**Comment by akhilkedia** [comment]
I have actually never faced this issue, but this should indeed be possible. I am not interested in coding this at the moment, but feel free to send a PR if you want.
Closing this assuming no PR.

**Comment by igel-kun** [comment]
The code seems right there on https://github.com/lennonhill/cookies-txt I'll try and hack something and make a PR :)

**Comment by akhilkedia** [comment]
Solved via https://github.com/akhilkedia/youtube-dl-firefox-addon/pull/7
